---
- name: this playbook depends on secrets
  connection: local
  hosts: localhost

  vars_files:
          - vars/vault.yml

  tasks:

          # actual value is "qwerty"
          - debug:
                  var: mysecret
            no_log: true                    # we will NOT see qwerty in our logs

          # actual value is "ansiblepass"
          - debug:
                  var: esxi_pass            # we WILL see ansiblepass in our logs
